### ISSUE TITLE
Topic required in `send` call for publisher connections breaks network transparency

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/iomanager#28]
I have a module in `trigger` that reads TPs from a file and pushes them out via `iomanager::SenderConcept<..>::send()`. In some of my test setups, the other end of the send is in the same application, and in other cases, the other end is in a different application, and connected via a publisher connection. But the publisher connection requires that the `send()` method is given a topic. This breaks network transparency (and makes the code more complicated because I have to pass the topic via configuration). If a topic is needed for a given connection, it should be handled transparently to the C++ code doing the sending

**Comment by eflumerf** [comment]
This was resolved with #29
